FROM node:22-alpine3.20 AS build
WORKDIR /app

COPY package*.json ./

# Instalar dependências
RUN npm install --frozen-lockfile

# Copiar código fonte
COPY . .

# Gerar build de desenvolvimento
RUN npm run build:dev

FROM nginx:1.28.0-alpine-slim
COPY --from=build /app/nginx /etc/nginx/conf.d
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]